version: '3'
services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
        environment:
            - discovery.type=single-node
        ports:
            - "9200:9200"
            - "9300:9300"
        networks:
            - elk
    kibana:
        image: docker.elastic.co/kibana/kibana:7.10.2
        ports:
            - "5601:5601"
        networks:
            - elk

networks:
    elk:
        driver: bridge
