const profiles = [
	{
		label: 'Airbnb',
		network: 'facebook',
		id: 'fb-profile-1',
		value: 'fb-profile-1',
		image: './brands/airbnb.png',
	},
	{
		label: 'McDonalds',
		network: 'facebook',
		id: 'fb-profile-2',
		value: 'fb-profile-2',
		image: './brands/mcdonalds.png',
	},
	{
		label: 'Amazon',
		network: 'facebook',
		id: 'fb-profile-3',
		value: 'fb-profile-3',
		image: './brands/amazon.png',
	},
	{
		label: 'Cisco',
		network: 'facebook',
		id: 'fb-profile-4',
		value: 'fb-profile-4',
		image: './brands/cisco.png',
	},
	{
		label: 'Chobani',
		network: 'instagram',
		id: 'ig-profile-1',
		value: 'ig-profile-1',
		image: './brands/chobani.png',
	},
	{
		label: 'Starbucks',
		network: 'instagram',
		id: 'ig-profile-2',
		value: 'ig-profile-2',
		image: './brands/starbucks.jpeg',
	},
	{
		label: 'Nike',
		network: 'instagram',
		id: 'ig-profile-3',
		value: 'ig-profile-3',
		image: './brands/nike.png',
	},
	{
		label: 'Prada',
		network: 'instagram',
		id: 'ig-profile-4',
		value: 'ig-profile-4',
		image: './brands/prada.png',
	},
	{
		label: 'Tesla',
		network: 'twitter',
		id: 'tw-profile-1',
		value: 'tw-profile-1',
		image: './brands/tesla.png',
	},
	{
		label: 'Apple',
		network: 'twitter',
		id: 'tw-profile-2',
		value: 'tw-profile-2',
		image: './brands/apple.png',
	},
	{
		label: 'IBM',
		network: 'twitter',
		id: 'tw-profile-3',
		value: 'tw-profile-3',
		image: './brands/ibm.png',
	},
	{
		label: 'Microsoft',
		network: 'twitter',
		id: 'tw-profile-4',
		value: 'tw-profile-4',
		image: './brands/microsoft.png',
	},
	{
		label: 'Alienware',
		network: 'youtube',
		id: 'yt-profile-1',
		value: 'yt-profile-1',
		image: './brands/alienware.png',
	},
	{
		label: 'Electronic Arts',
		network: 'youtube',
		id: 'yt-profile-2',
		value: 'yt-profile-2',
		image: './brands/electronic-arts.jpeg',
	},
	{
		label: 'Nvidia',
		network: 'youtube',
		id: 'yt-profile-3',
		value: 'yt-profile-3',
		image: './brands/nvidia.png',
	},
	{
		label: 'Louis Vuitton',
		network: 'youtube',
		id: 'yt-profile-4',
		value: 'yt-profile-4',
		image: './brands/louis-vuitton.png',
	},
]

export default profiles
